// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('pinkman-passwor-services-test-1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('pinkman-passwor-services-test-1', async function() {
    // Test name: pinkman-passwor-services-test-1
    // Step # | name | target | value
    // 1 | open | / |
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1440x875 |
    await driver.manage().window().setRect({ width: 1440, height: 875 })
    // 3 | click | id=generate-btn |
    await driver.findElement(By.id("generate-btn")).click()
    // 4 | type | id=password-input | s#$o9Qis5
    await driver.findElement(By.id("password-input")).sendKeys("s#$o9Qis5")
    // 5 | click | id=submit-btn |
    await driver.findElement(By.id("submit-btn")).click()
    // 6 | click | id=generated-password-input |
    await driver.findElement(By.id("generated-password-input")).click()
    // 7 | click | id=submit-btn |
    await driver.findElement(By.id("submit-btn")).click()
    // 8 | click | id=generate-btn |
    await driver.findElement(By.id("generate-btn")).click()
    // 9 | click | id=password-input |
    await driver.findElement(By.id("password-input")).click()
    // 10 | type | id=password-input | p)r32Xf#tB3
    await driver.findElement(By.id("password-input")).sendKeys("p)r32Xf#tB3")
    // 11 | click | id=submit-btn |
    await driver.findElement(By.id("submit-btn")).click()
    // 12 | mouseOver | id=submit-btn |
    {
      const element = await driver.findElement(By.id("submit-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 13 | mouseOut | id=submit-btn |
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 14 | click | css=.btn-secondary |
    await driver.findElement(By.css(".btn-secondary")).click()
    // 15 | type | id=password-input | rafa
    await driver.findElement(By.id("password-input")).sendKeys("rafa")
    // 16 | click | id=submit-btn |
    await driver.findElement(By.id("submit-btn")).click()
    // 17 | type | id=password-input | Rafael12@
    await driver.findElement(By.id("password-input")).sendKeys("Rafael12@")
    // 18 | click | id=submit-btn |
    await driver.findElement(By.id("submit-btn")).click()
  })
})
