name: Main to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js and Yarn
      uses: actions/setup-node@v16.15.1
      with:
        node-version: '16.x'
        cache: 'yarn'

    - name: Install dependencies and build
      run: |
        yarn install
        yarn build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: dist
        token: ${{ secrets.GITHUB_TOKEN }}
